[package]
name = "chordsense-iod"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "chordsense-iod"
path = "src/main.rs"

[dependencies]
spidev = "0.7"
hound = "3.5"
rodio = { version = "0.22.2", default-features = false, features = ["playback", "symphonia-all", "experimental"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libc = "0.2"
